# Set semantic version number according to change made
#
# format: MAJOR.MINOR.PATCH
#
# Conventions: Major - Increment for breaking change in public interface
#			   Minor - Increment for backwards-compatible new feature
#			   Patch - Increment for build (automatically by Appveyor)
version: 1.0.{build}
configuration: Release
platform: Any CPU
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true
  
clone_depth: 1

cache:
 - packages -> **\packages.config
 
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
 - ps: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
deploy:
- provider: NuGet
  api_key:
    secure: 8nOJ8wjmitnOcDwlirh5QLHECezb9AQgSzbXbBsNkOBGhtOxz1WDQKBDOZXIhoM9
  on:
    branch: master